# Generated by Django 5.1 on 2024-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_in_cas', models.DateTimeField()),
                ('lokacija', models.CharField(choices=[('119', 'KOPER'), ('221', 'LJUBLJANA'), ('150', 'CELJE'), ('185', 'NOVO MESTO'), ('212', 'MARIBOR')], max_length=4)),
                ('kategorija', models.CharField(choices=[('4', 'A'), ('6', 'B'), ('14', 'D')], max_length=2)),
            ],
        ),
    ]
