# Generated by Django 5.1 on 2024-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datumi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='st_mest',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
