# Generated by Django 5.1 on 2024-08-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datumi', '0002_termin_st_mest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casovnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokacija', models.CharField(choices=[('119', 'KOPER'), ('221', 'LJUBLJANA'), ('150', 'CELJE'), ('185', 'NOVO MESTO'), ('212', 'MARIBOR')], max_length=4)),
                ('kategorija', models.CharField(choices=[('4', 'A'), ('6', 'B'), ('14', 'D')], max_length=2)),
                ('timedelta', models.IntegerField(max_length=3, null=True)),
            ],
        ),
    ]
