# Generated by Django 5.1 on 2024-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datumi', '0003_casovnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casovnica',
            name='timedelta',
            field=models.IntegerField(default=999, max_length=3),
        ),
    ]
