# Generated by Django 5.1 on 2024-08-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(choices=[('A', 'A'), ('A1', 'A1'), ('A2', 'A2'), ('AM', 'AM'), ('B', 'B'), ('B1', 'B1'), ('BE', 'BE'), ('C', 'C'), ('C1', 'C1'), ('C1E', 'C1E'), ('CE', 'CE'), ('D', 'D'), ('D1', 'D1'), ('DE', 'DE'), ('D1E', 'D1E'), ('F', 'F'), ('G', 'G')], max_length=3)),
                ('območje', models.CharField(choices=[('Območje 1', 'Območje 1'), ('Območje 2', 'Območje 2'), ('Območje 3', 'Območje 3'), ('Območje 4', 'Območje 4'), ('Območje 5', 'Območje 5')], max_length=9)),
                ('lokacija', models.CharField(choices=[('test', 'test'), ('tes', 'tes')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
