# Generated by Django 5.1 on 2024-08-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uporabnik',
            name='območje',
            field=models.CharField(choices=[('Območje 1', 'Območje 1'), ('Območje 2', 'Obmocje 2'), ('Območje 3', 'Območje 3'), ('Območje 4', 'Območje 4'), ('Območje 5', 'Območje 5')], max_length=9),
        ),
    ]
