# Generated by Django 5.1 on 2024-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_alter_uporabnik_kategorija_alter_uporabnik_območje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uporabnik',
            name='območje',
        ),
        migrations.AddField(
            model_name='uporabnik',
            name='obmocje',
            field=models.IntegerField(blank=True, default=17, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='kategorija',
            field=models.CharField(choices=[('4', 'A'), ('6', 'B'), ('14', 'D')], max_length=3),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='lokacija',
            field=models.CharField(choices=[('119', 'KOPER'), ('221', 'LJUBLJANA'), ('150', 'CELJE'), ('185', 'NOVO MESTO'), ('212', 'MARIBOR')], max_length=9),
        ),
    ]
